name: C Build CI

on:
  push:
     branches: ["main"]
  push_request: 
     branches: ["main"]

jobs:
   build:

       runs-on: ubuntu-latest

       steps:

       - name: Checkout code
         uses: actions/checkout@v3

       - name: Install GCC
         run: sudo apt update && sudo apt install build-essential

       - name: Build project
         run: make

       - name: Run executable
         run: ./main
